- .github/worksflows/blossom-ci.yml
> Adding Blossom Workflow

- .gitignore
- examples/README.md
- examples/earth2mip.def
- examples/notebooks/01_ensemble_inference.ipynb
- examples/notebooks/02_model_comparison.ipynb
Adding Apptainer build for those that cannot run docker.
Closes: https://github.com/NVIDIA/earth2mip/issues/5
> Apptainer build + notebook improvements

- README.md
Fixing some issues with the main readme
Closes: https://github.com/NVIDIA/earth2mip/issues/11 
Closes: https://github.com/NVIDIA/earth2mip/issues/13
> fix: Readme update and fixes

- CHANGELOG.md
- examples/notebooks/01_ensemble_inference.ipynb
- examples/notebooks/02_model_comparison.ipynb
- setup.cfg
Adding ECMWF libs for CDS access to pyproject.
Closes: https://github.com/NVIDIA/earth2mip/issues/16
ecmwflibs - [Apache-2.0 license](https://github.com/ecmwf/ecmwflibs/blob/master/LICENSE)
h5netcdf - [BSD-3-Clause license](https://github.com/h5netcdf/h5netcdf/blob/main/LICENSE)
> fix: Update deps to include CDS libs

- earth2mip/networks/pangu.py
- examples/workflows/dlwp.py
- examples/workflows/fcnv2_sm.py
- examples/workflows/pangu_24.py
Fixing workflow script to function.
Closes: https://github.com/NVIDIA/earth2mip/issues/17
Closes: https://github.com/NVIDIA/earth2mip/issues/23
> fix: fixing workflow scripts

- examples/notebooks/01_ensemble_inference.ipynb
Closes: https://github.com/NVIDIA/earth2mip/issues/27
> Fixing colormap in notebook 1

- examples/README.md
- examples/earth2mip.def
Closes: https://github.com/NVIDIA/earth2mip/issues/22
> Improving Examples Singularity Doc and Conda Env

- earth2mip/networks/pangu.py
Fixing minor bug in pangu inferencer to work in ensemble notebook.
Closes: https://github.com/NVIDIA/earth2mip/issues/29
> fix: fixing pangu forward bug

- examples/notebooks/01_ensemble_inference.ipynb
Closes: https://github.com/NVIDIA/earth2mip/issues/45
> Fix: Remove CLI command from Notebook 1 and instead rely on Python API

- examples/notebooks/01_ensemble_inference.ipynb
- examples/workflows/dlwp.py
a typo and something that excepted IC for linting\
Closes: https://github.com/NVIDIA/earth2mip/issues/49
> some minor fixes

- README.md
- earth2mip/inference_ensemble.py
- earth2mip/networks/__init__.py
- earth2mip/regrid.py
- tests/test_end_to_end.py
> Fix grid bug with run_basic_inference

- earth2mip/networks/__init__.py
- earth2mip/networks/pangu.py
- examples/workflows/model_nudging.py
- examples/workflows/run_ensemble_model_noise.py
This PR adds a file that was not committed in [PR77](https://github.com/NVIDIA/earth2mip/pull/77) and closes issue #84 by applying source to both dimensional and non dimensional state vectors
> add scale and center to model perturb examples

- Makefile
- README.md
- earth2mip/networks/fcnv2_sm.py
- pyproject.toml
Closes: https://github.com/NVIDIA/earth2mip/issues/107
> CI Updates

- .pre-commit-config.yaml
- Makefile
- pyproject.toml
Just enables mypy with pre-commit, make file and pyproject toml. Getting all files up to standard will take much more work and can be done iteratively.
Any new files going forward will need to pass mypy.
Closes: https://github.com/NVIDIA/earth2mip/issues/52
> Adding MyPy

- README.md
- pyproject.toml
- requirements.txt
Closes: https://github.com/NVIDIA/earth2mip/issues/80
> Modulus Release Update

- pyproject.toml
> fix graphcast jax

- docs/userguide/install.md
> Install notes improvements

- examples/03_model_scoring.py
Minor fixes to example 3 in the docs
Closes: https://github.com/NVIDIA/earth2mip/issues/122
> Fix: Fixing Example 3 docs

- CHANGELOG.md
- examples/04_diagnostic_models.py
- pyproject.toml
Closes: https://github.com/NVIDIA/earth2mip/issues/119
> Adding Diagnostic Model Example

- README.md
just updating the readme as I am reading it
> update readme gc link from Arxiv to Science

- .pre-commit-config.yaml
- docs/userguide/index.md
- docs/userguide/inference-workflows.rst
- earth2mip/inference_ensemble.py
- earth2mip/schema.py
- earth2mip/time_collection.py
- test/_regtest_outputs/test_time_collection.test_run_over_initial_times.out
- test/test_time_collection.py
Closes #166. Allows user to more easily to use the multiple initial condition workflow with their own data and model.
> Add python API for the time collection

- docs/modules/index.rst
- examples/01_ensemble_inference.py
> Minor Updates to Example 1 for GFS datasource

- earth2mip/networks/pangu.py
- pyproject.toml
> Adding dtype to pangu
